name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: granovetter
          environment-file: environment.conda.yml
          auto-activate-base: false
          use-mamba: true

      - name: Verify core imports
        shell: bash -l {0}
        run: |
          python -c "import numpy, matplotlib, scipy, networkx, streamlit"

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -q
